In [26]:
import numpy as np

In [27]:
data = []
with open('data.txt' , 'r') as f:
    for line in f.readlines():
        data.append(line.strip('\n'))

In [28]:
choices = []
for student in data[6 : len(data) - 3]:
    choice = []
    student_split = student.split(' ')
    for c in student_split[-5 : ]:
        if '[' in c:
            choice.append(int(c[1]))
        elif ']' in c:
            choice.append(int(c[0]))
        else:
            choice.append(int(c))
    choices.append(np.array(choice))
choices = np.array(choices)   
choices   

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 1, 1],
       [0, 0, 1, 0, 0],
       [0, 0, 1, 0, 1],
       [0, 0, 1, 1, 0],
       [0, 0, 1, 1, 1],
       [0, 1, 0, 0, 0],
       [0, 1, 0, 0, 1],
       [0, 1, 0, 1, 0],
       [0, 1, 0, 1, 1],
       [0, 1, 1, 0, 0],
       [0, 1, 1, 0, 1],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 1, 1],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 1, 0],
       [1, 0, 0, 1, 1],
       [1, 0, 1, 0, 0],
       [1, 0, 1, 0, 1],
       [1, 0, 1, 1, 0],
       [1, 0, 1, 1, 1],
       [1, 1, 0, 0, 0],
       [1, 1, 0, 0, 1],
       [1, 1, 0, 1, 0],
       [1, 1, 0, 1, 1],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 0, 1],
       [1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1]])

In [29]:
choices.shape

(32, 5)

In [30]:
cumulative = []

cum1 = data[3].strip(' ')
cum2 = data[4].strip(' ')[:-1]
cum1 = cum1.strip('[')
cum2 = cum2.strip(']')
cum = cum1 + cum2
cum_split = cum.split(',')
for c in cum_split:
    cumulative.append(int(c))

cumulative = np.array(cumulative)
cumulative

array([   3,    9,   11,   22,   23,   24,   27,   31,   32,   40,   40,
         56,   56,   59,   61,   76,   86,  115,  129,  210,  213,  241,
        256,  336,  352,  408,  429,  602,  613,  674,  702, 1000])

In [31]:
dis_freq = []
dis_freq.append(cumulative[0])
for i in range(len(cumulative) - 1):
    dis_freq.append(cumulative[i + 1] - cumulative[i])

dis_freq = np.array(dis_freq)
dis_freq

array([  3,   6,   2,  11,   1,   1,   3,   4,   1,   8,   0,  16,   0,
         3,   2,  15,  10,  29,  14,  81,   3,  28,  15,  80,  16,  56,
        21, 173,  11,  61,  28, 298])

In [32]:
data_matrix = []

for idx in range(len(dis_freq)):
    for i in range(dis_freq[idx]):
        data_matrix.append(choices[idx])

data_matrix  = np.array(data_matrix)

In [33]:
with open('cleaned_data.csv' , 'w') as f:
    for idx in range(len(dis_freq)):
        for i in range(dis_freq[idx]):
            for idx2 , j in enumerate(choices[idx]):
                if idx2 != len(choices[idx]) - 1:
                    f.write(str(j) + ' ')
                else:
                    f.write(str(j))
            f.write('\n')
            